name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    name: Configure matrix
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Read tags file
        id: get-tags
        run: |
          echo ::set-output name=tags::$(cat tags.json)
    outputs:
      tags: ${{ steps.get-tags.outputs.tags }}

  run-tests:
    needs: generate-matrix
    runs-on: ubuntu-latest
    name: Build images
    env:
      PHP_IMAGE_TAG: ${{ matrix.tag }}
    strategy:
      fail-fast: false
      matrix:
        tag: ${{ fromJson(needs.generate-matrix.outputs.tags) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - name: Log in to DockerHub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Test image
        uses: docker/bake-action@master
        with:
          targets: test
          set: |
            test.cache-from=type=gha,scope=${{ matrix.tag }}
            test.cache-to=type=gha,mode=max,scope=${{ matrix.tag }}

      - name: Push image
        uses: docker/bake-action@master
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          push: true
