name: Update tags

on:
  workflow_dispatch:
  schedule:
    - cron: '30 7 * * *'
  push:
    branches: [main]

jobs:
  nightly-builds:
    runs-on: ubuntu-latest
    name: Update
    steps:
      - name: Check out source
        uses: actions/checkout@master

      - name: Set up PHP
        uses: shivammathur/setup-php@v2

      - name: Update tags
        run: php get-tags.php > tags.json

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Automatic tag update
          title: ":robot: Tag update"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
